net_name: yolov5s
dataset: per_class
optimizer_type: SGD
num_workers: 8
weight_decay: 0
grad_clip: true
img_size: 640
batch_size: 32
seed: 42
decay_type: step
warmup_steps: 100
step_size: 30
max_grad_norm: 1.0
learning_rate: 1.0e-06
local_epoch: 5
server_local_epoch: 5
epoch: 50
clients:
- 56
- 60
central: '1'
weights: /hdd/hdd3/coco_fl/best.pt
yolo_cfg: fedmodels/yolov5/models/yolov5s.yaml
data_conf: data/coco_custom.yaml
yolo_hyp: fedmodels/yolov5/data/hyps/hyp.scratch-low.yaml
shuffle: false
save_dir: ./exp/
wandb: true
project: FedYOLO
