wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.11
    start_time: 1667994576.854529
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 13
      - 16
      - 23
      4: 3.8.11
      5: 0.13.4
      8:
      - 5
batch_size:
  desc: null
  value: 32
epoch:
  desc: null
  value: 50
learning_rate:
  desc: null
  value: 1.0e-06
local_epoch:
  desc: null
  value: 1
server_epoch:
  desc: null
  value: 1
